updating documentation for UI-Toolkit react controls
open-amt-cloud-toolkit/docs pull request #125
Opened 2021-08-10 23:48 UTC by vyshali-chitikeshi

Updated documentation for Ui-Toolkit react controls.

2021-08-11 15:42 UTC, rsdmike requested changes

2021-08-11 15:42 UTC, rsdmike commented on docs/Tutorials/uitoolkit.md
> +    npm install https://github.com/open-amt-cloud-toolkit/ui-toolkit-react
this needs to be `@open-amt-cloud-toolkit/ui-toolkit-react'

2021-08-11 18:41 UTC, vyshali-chitikeshi commented
Requested changes made

2021-08-12 23:41 UTC, rsdmike approved these changes

2021-08-12 23:41 UTC, merged