refactor(api): tutorial from nodejs to curl
open-amt-cloud-toolkit/docs pull request #138
Opened 2021-08-19 19:56 UTC by bwendlandt-intel

## PR Checklist

- [x] Leverages formatting as provided by https://squidfunk.github.io/mkdocs-material/reference/abbreviations/ 
- [x] Have viewed and verified edits in rendered form ensuring proper formatting

## What are you changing?

- Move api tutorial to curl to simplify

## Anything the reviewer should know when reviewing this PR?

2021-09-08 20:21 UTC, kimberlyxdavis requested changes

2021-09-08 20:21 UTC, kimberlyxdavis commented on docs/Tutorials/apiTutorial.md
> +The sample GET and POST curl commands below can be adapted for other MPS and RPS methods **by changing the URI path and modifying the request body data, if applicable**.
Do you mean URL here, or is it a considered a URI in this context? Typo or intentional?

2021-09-08 20:21 UTC, kimberlyxdavis commented on docs/Tutorials/apiTutorial.md
> +        Because we are using self-signed certificates for MPS for development purposes, we must supply this flag to force past certificatverification.
certificate verification? Or again, like the one about URI vs. URL below, am I responding to something intentional?

Like is there some thing called certificatverification?

2021-09-08 21:10 UTC, rsdmike approved these changes

2021-09-14 21:05 UTC, Kimberly-Davis approved these changes

2021-09-14 21:06 UTC, Kimberly-Davis approved these changes

2021-09-14 21:10 UTC, kimberlyxdavis approved these changes

2021-09-14 21:15 UTC, merged