docs(eks): added scaling in eks
open-amt-cloud-toolkit/docs pull request #144
Opened 2021-09-07 16:27 UTC by brianosburn-intel

closes AB#3476

## PR Checklist

- [x ] Leverages formatting as provided by https://squidfunk.github.io/mkdocs-material/reference/abbreviations/ 
- [x ] Have viewed and verified edits in rendered form ensuring proper formatting

## What are you changing?

adding k8 support for Amazon AWS

## Anything the reviewer should know when reviewing this PR?

2021-09-08 16:05 UTC, bwendlandt-intel commented
@rsdmike Am I able to get access to our AWS instance to test this or are we limited on users?

2021-09-08 17:22 UTC, kimberlyxdavis requested changes

2021-09-08 17:22 UTC, kimberlyxdavis commented on docs/Kubernetes/deployingk8s-eks.md
> +This tutorial demonstrates how to deploy the Open AMT Cloud Toolkit on a Kubernetes cluster using EKS. Alternatively, you can also perform a simpler, test deployment using a single-node cluster local
The thing I might question here is phrasing this as "alternatively".  We're trying to get away from phrasing things as in "you can do it this way and that way and whatever way". It's confusing to the user. 

To make this sound like a separate thing, I might say: 
To perform a simpler test deployment, use a single-mode cluster locally. See [ ].

2021-09-08 17:22 UTC, kimberlyxdavis commented on docs/Kubernetes/deployingk8s-eks.md
> +Perform the following command to create a new EKS cluster as well as supporting components.
Even shorter:

Create a new EKS cluster and supporting components:

2021-09-08 17:22 UTC, kimberlyxdavis commented on docs/Kubernetes/deployingk8s-eks.md
> +### 2. Configure VPC for access
What's the VPC again? Virtual Private Cloud?

2021-09-08 17:22 UTC, kimberlyxdavis commented on docs/Kubernetes/deployingk8s-eks.md
> +1. go to [RDS home](https://console.aws.amazon.com/rds/home)
Why are these sentences lower case? Is there a open source convention reason?

2021-09-08 17:22 UTC, kimberlyxdavis commented on docs/Kubernetes/deployingk8s-eks.md
> +Where:
Parameters:

2021-09-08 17:22 UTC, kimberlyxdavis commented on docs/Kubernetes/deployingk8s-eks.md
> +Enable persistant storage in the cluster be following the steps provided in the following [guide](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html).
Spelling: persistent

2021-09-08 17:22 UTC, kimberlyxdavis commented on docs/Scaling/overview.md
> +    The EKS deployment section is not a tutorial for beginners. It intended for those who have prior knowledge of the service. To begin learning about EKS, start with [Amazon Elastic Kubernetes Servi
It is intended

2021-09-08 17:22 UTC, kimberlyxdavis commented on docs/Scaling/overview.md
> +[Get Started with EKS](../Kubernetes/deployingk8s-eks.md){: .md-button .md-button--primary target="_blank"}
Lastly, I would just say try to be consistent ending complete sentences with periods unless they are a heading and using colons appropriately.

2021-09-14 21:13 UTC, kimberlyxdavis approved these changes

2021-09-14 21:16 UTC, merged