docs:rpc-go updates and maintenance command
open-amt-cloud-toolkit/docs pull request #170
Opened 2021-11-02 00:28 UTC by Kimberly-Davis

## PR Checklist

- [ ] Leverages formatting as provided by https://squidfunk.github.io/mkdocs-material/reference/abbreviations/ 
- [ ] Have viewed and verified edits in rendered form ensuring proper formatting

## What are you changing?

docs/GetStarted/buildRPC.md
 .\docs\Reference\RPC\commandsRPC.md
mkdocs.yml
## Anything the reviewer should know when reviewing this PR?

**Yes. Plenty!**

I was not able to test the Linux commands. My linux system is non-operational at the moment, and the OS has to be re-installed.
@rsdmike Can you take a look at the Docker (On Linux Host Only) in buildRPC.md. I don't know what I'm doing there.

@matt-primrose @rsdmike 
Can you take a look at the tables in the amtinfo section of the commandsRPC.md. BW mentioned that you might have some interesting insights into what might go in the description section of these tables. 

I had a hard time deciding if I should do this or not, but I wanted to try exhaustively documenting this application. What does that look like? Can we keep the two things in sync?

@bwendlandt-intel @madhavilosetty-intel 
I think any insight you have will be greatly appreciated.

2021-11-02 16:39 UTC, matt-primrose commented on docs/Reference/RPC/commandsRPC.md
> +| -f | DNS suffix override |
this should be -d

2021-11-08 16:18 UTC, rsdmike submitted a review, later dismissed

2021-11-08 16:18 UTC, rsdmike commented on docs/GetStarted/buildRPC.md
> +        placeholder for Mike
```suggestion 
sudo docker run --device=/dev/mei0 rpc-go:latest version
```

2021-11-08 16:18 UTC, rsdmike commented on docs/GetStarted/buildRPC.md
> +        placeholder for Mike
```suggestion 
docker build -f "Dockerfile" -t rpc-go:latest .
```

2021-11-08 17:08 UTC, bwendlandt-intel requested changes

2021-11-08 17:08 UTC, bwendlandt-intel commented on docs/GetStarted/buildRPC.md
> +   git clone --recursive https://github.com/open-amt-cloud-toolkit/rpc-go
Don't need --recursive

2021-11-08 17:08 UTC, bwendlandt-intel commented on docs/GetStarted/buildRPC.md
> +    === "Docker (On Linux Host Only)"
Can we move Docker to after Windows for these tabbed sections? Linx+Windows is our preferred GSG path

2021-11-08 17:08 UTC, bwendlandt-intel commented on docs/GetStarted/buildRPC.md
> +        sudo rpc version
Double check all the Linux cmds, they need to be 'sudo ./rpc cmd-here', ./ is requried

2021-11-08 17:18 UTC, matt-primrose approved these changes

2021-11-08 17:40 UTC, bwendlandt-intel approved these changes

2021-11-09 03:02 UTC, merged