docs(rpc-go): refining rpc-go commands
open-amt-cloud-toolkit/docs pull request #191
Opened 2021-11-20 00:00 UTC by Kimberly-Davis

## PR Checklist

- [ ] Leverages formatting as provided by https://squidfunk.github.io/mkdocs-material/reference/abbreviations/ 
- [ ] Have viewed and verified edits in rendered form ensuring proper formatting

## What are you changing?

        modified:   docs/GetStarted/buildRPC.md

## Anything the reviewer should know when reviewing this PR?

RB ran into a few gotchas, which this check-in should fix.

2021-11-22 16:17 UTC, bwendlandt-intel requested changes

2021-11-22 16:17 UTC, bwendlandt-intel commented on docs/GetStarted/buildRPC.md
> +If you have already cloned the toolkit repository as described in [Set Up](setup.md), change to the cloned `rpc-go` directory and see [Build the RPC](#buildtherpc).
You don't actually need to reference an anchor, the markdown headings have this built in, you can reference (#build-the-rpc)

2021-11-22 16:17 UTC, bwendlandt-intel commented on docs/GetStarted/buildRPC.md
> +##  <a name="buildtherpc"></a>Build the RPC
Remove anchor

2021-11-22 16:17 UTC, bwendlandt-intel commented on docs/GetStarted/buildRPC.md
> +        rpc version
We need the '.\\' on all Windows cmds, while Command Prompt doesn't care one way or the other, it is for Powershell.  This allows the copy/paste to work across both.

2021-11-22 16:17 UTC, bwendlandt-intel commented on docs/GetStarted/buildRPC.md
> +2. Copy to the executable to a managed device.
Grammar: 'Copy the executable...'

2021-11-29 21:16 UTC, rjbrache approved these changes
These mods add clarity.  Fix BW's findings and things look good from a content and flow perspective.

2021-11-30 00:08 UTC, bwendlandt-intel approved these changes

2021-11-30 16:18 UTC, merged