docs: 2.7 release notes
open-amt-cloud-toolkit/docs pull request #254
Opened 2022-12-05 16:17 UTC by matt-primrose

## PR Checklist

- [x] Leverages formatting as provided by https://squidfunk.github.io/mkdocs-material/reference/abbreviations/ 
- [ ] Have viewed and verified edits in rendered form ensuring proper formatting

## What are you changing?

## Anything the reviewer should know when reviewing this PR?

2022-12-05 22:46 UTC, rsdmike requested changes

2022-12-05 22:46 UTC, rsdmike commented on docs/release-notes.md
> +:material-star:** Customer Request: Health check improvement **
Service Startup Improvement

2022-12-05 22:46 UTC, rsdmike commented on docs/release-notes.md
> +We have added a maintenance task that will enable syncing the OS Hostname and AMT Hostname.  When this command is run, if the OS and AMT hostnames are different, the OS hostname will be applied to AM
fqdn => FQDN

2022-12-08 16:48 UTC, Kimberly-Davis reviewed
Hey,

Overall great.  A very light edit, Matt. Where I could, I tried to reduce a few words. You've all decided to make this a very personal, authentic-sounding release notes doc, and I want to support you in that. Casual can get slightly verbose though, and it's what make so much online writing and instructional YouTube videos insufferable. 

Anyway, looks like the team is doing great. 

Regards,
Kimberly

2022-12-08 16:48 UTC, Kimberly-Davis commented on docs/release-notes.md
> +We have added a maintenance task that will enable syncing the OS Hostname and DNS Suffix with AMT Hostname and DNS Suffix.  When this command is run, if the OS and AMT host names are different, the O
We added a maintenance task command that enables syncing the OS hostname and DNS Suffix with AMT hostname and DNS suffix.  If the OS and AMT hostnames are different when the command is run, the OS hostname will be applied to AMT.  This maintenance task enables AMT to respond to network requests that use the fully qualified domain name (FQDN) of the device.

Hey @matt-primrose, do you want to mention the name of the command here?

2022-12-08 16:48 UTC, Kimberly-Davis commented on docs/release-notes.md
> +Both RPS and MPS will now check for dependent services to be available before starting up.  If a dependent service is not available, they will wait and retry after a few seconds.  If after 10 attempt
Both RPS and MPS now check for dependent services available before starting up.  If a dependent service is not available, the RPS and MPS wait and retry after a few seconds.  After 10 retry attempts the service shuts down.  In a production deployment, this shutdown typically triggers a restart of the service, starting the cycle again until dependent services are available. Retry attempts are listed in the service logs.

2022-12-08 16:48 UTC, Kimberly-Davis commented on docs/release-notes.md
> +A big thank you to Orin from [Laplink](https://www.laplink.com/) for both filing and fixing several MPS issues!  We love getting customer feedback as well as customer contributions.  When we get cust
A big thank you to Orin from [Laplink](https://www.laplink.com/) for both filing and fixing several MPS issues!  We love getting customer feedback as well as customer contributions.  Customers filing issues and then immediately contributing the fix, well, that is what open source is all about!

2022-12-10 07:42 UTC, rsdmike approved these changes

2022-12-10 07:42 UTC, merged