docs(ui-toolkit): update bundles
open-amt-cloud-toolkit/docs pull request #41
Opened 2021-03-25 01:23 UTC by bwendlandt-intel

## PR Checklist

- [x] Leverages formatting as provided by https://squidfunk.github.io/mkdocs-material/reference/abbreviations/ 
- [x] Have viewed and verified edits in rendered form ensuring proper formatting

## What are you changing?

- Update styling of KVM/SOL bundle docs to match docs
- Update code snippets to match 1.1 or newer changes i.e. server -> mpsServer
- Initial formatting fix for localization.md

## Anything the reviewer should know when reviewing this PR?
Bundles outside of KVM and SOL are being deprecated, correct?

2021-03-26 22:58 UTC, kimberlyxdavis commented on docs/UIToolkit/Bundles/CIRAConfigs.md
> +## Run in Development Enviroment
Environment, with an "n"

2021-03-26 22:59 UTC, kimberlyxdavis commented on docs/UIToolkit/Bundles/CIRAConfigs.md
> +To add and test new changes before bundling the control, a webpack dev server can be used.
To add and test new changes before bundling the control, use a webpack dev server.

2021-03-26 23:04 UTC, kimberlyxdavis commented on docs/UIToolkit/Bundles/DeviceGrid.md
> +- [A MPS Server with an AMT Device Connected](../../../Docker/dockerLocal/)
"An MPS Server" or just "MPS Server"

2021-03-26 23:05 UTC, kimberlyxdavis commented on docs/UIToolkit/Bundles/DeviceGrid.md
> +## Run in Development Enviroment
"Enviroment" should be "Environment"

2021-03-26 23:07 UTC, kimberlyxdavis commented on docs/UIToolkit/Bundles/CIRAConfigs.md
> +4. Open a new Chrome* browser and navigate to the following url:
URL

2021-03-26 23:13 UTC, kimberlyxdavis commented on docs/UIToolkit/Bundles/CIRAConfigs.md
> +To add and test new changes before bundling the control, a webpack dev server can be used.
I know it sounds trivial, but the way it's written it sounds as if the web dev server is driving the action when it's the user.

2021-03-26 23:15 UTC, kimberlyxdavis commented on docs/UIToolkit/Bundles/DeviceGrid.md
> +- Compilation errors if the ui-toolkit was not downloaded and installed into your react app.
I would make all these complete sentences or fragments.

2021-03-26 23:21 UTC, kimberlyxdavis commented on docs/UIToolkit/localization.md
> +If a user's web console is already enabled with localization, please make sure to add the [translations](https://github.com/open-amt-cloud-toolkit/ui-toolkit/tree/master/public/locales) of UI-control
If your web console is already enabled with localization, please make sure to add the [translations](https://github.com/open-amt-cloud-toolkit/ui-toolkit/tree/master/public/locales) of UI-controls into your web console's translations file.

2021-03-26 23:22 UTC, kimberlyxdavis requested changes
Many of these smallish errors got propagated throughout the multiple files. I didn't call them out each time. You'll see.

2021-03-31 23:56 UTC, kimberlyxdavis approved these changes

2021-04-05 18:00 UTC, madhavilosetty-intel approved these changes

2021-04-05 18:07 UTC, merged