docs: first of several corrections to the scaling instructions
open-amt-cloud-toolkit/docs pull request #77
Opened 2021-05-25 22:58 UTC by kimberlyxdavis

## PR Checklist

- [ ] Leverages formatting as provided by https://squidfunk.github.io/mkdocs-material/reference/abbreviations/ 
- [ ] Have viewed and verified edits in rendered form ensuring proper formatting

## What are you changing?

        modified:   docs/Kubernetes/kubernetes.md
        modified:   docs/assets/images/HighLevelArchitectureSID.png
        modified:   docs/assets/images/HighLevelArchitectureScaling.png

Corrected for general structure in anticipation of new instructions. 

## Anything the reviewer should know when reviewing this PR?

2021-06-19 01:30 UTC, matt-primrose commented
@kimberlyxdavis merge conflicts have been resolved.

2021-06-23 21:39 UTC, rsdmike requested changes
After building the docker images, i think linking to the two deployment options is the right move. Local or AKS

2021-06-23 21:39 UTC, rsdmike commented on docs/Kubernetes/kubernetes.md
> +### Prerequisites
these scripts no longer exists

2021-06-23 21:39 UTC, rsdmike commented on docs/Kubernetes/kubernetes.md
> +### Steps to Deploy
steps to deploy has changed.

2021-06-25 15:57 UTC, closed without merging